config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :domains do
    resources :a_records
  end
  #sessions
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  #Sign up
  get '/signup' => "users#new"
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show', as: 'user'
 end

app/models/a_record.rb
class ARecord < ApplicationRecord
  belongs_to :domain
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  belongs_to :user
  has_many :a_records
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :domains
  has_many :a_records
end

app/controllers/a_records_controller.rb
class ARecordsController < ApplicationController
  HEADERS = { 'X-NSONE-Key' => ENV['API_KEY']}
  def new
  end

  def create
    domain = Domain.find_by(id: params[:domain_id])
    if current_user.id == domain.user_id  
      response = Unirest.put("#{ENV['API_ROOT_URL']}/#{domain.domain_name}/#{domain.domain_name}/A
                              ", headers: HEADERS,
                                parameters: { zone: "#{domain.domain_name}", 
                                              domain:"#{domain.domain_name}",
                                              type: "A",
                                              answers: [{answer: ["#{params[:ip_address]}"]}] }.to_json)
      if response.code == 200 
        @a_record = ARecord.create(ip_address: params[:ip_address], 
                                   domain_id: domain.id,
                                   user_id: current_user.id )
        redirect_to domain_a_record_path(domain_a_record)
      end
    else
      redirect_to domain_a_record_path(new_domain_a_record)
    end
  end

  def show
    @a_record = ARecord.find(params[:id])
    unless current_user.id = @a_record.user_id
      redirect_to root_path
    end
  end

  def edit
    @domain = Domain.find(params[:domain_id])
  end

  def update
    a_record = ARecord.find(params[:id])
    response = Unirest.post("#{ENV['API_ROOT_URL']}/#{domain.domain_name}/#{domain.domain_name}/A
                              ", headers: HEADERS,
                                parameters: { answers: [{answer: ["#{params[:ip_address]}"]}] }.to_json)
    if response.status == 200
      a_record.update(ip_address: params[:ip_address])
      redirect_to domain_a_record_path(domain_a_record)
    else
      render :edit
    end
  end

  def destroy
    a_record = ARecord.find(params[:id])
    if current_user.id == a_record.user_id
      response = Unirest.delete("#{ENV['API_ROOT_URL']}/#{a_record.domain.domain_name}/#{a_record.domain.domain_name}/A", headers: HEADERS)
      if response.code == 200
        a_record.destroy
      else
        redirect_to domain_a_record_path(domain_a_record)
      end
    else
    redirect_to domain_path(domain)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
  def authenticate_user!
    redirect_to '/login' unless current_user
  end

  include SessionsHelper
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  skip_before_action :verify_authenticity_token
  HEADERS = { 'X-NSONE-Key' => ENV['API_KEY']}

  def new
  end

  def create
    response = Unirest.put("#{ENV['API_ROOT_URL']}/#{params[:domain_name]}", 
                        headers: HEADERS, 
                        parameters:{ zone: "#{params[:domain_name]}"}.to_json)
    if response.code == 200 #if request is successful, create domain in DB
      domain = Domain.create(user_id: current_user.id, domain_name: params[:domain_name])
      redirect_to domain_path(domain)
    else
      #error: your domain did not register
      redirect_to user_path(current_user)
    end
  end

  def show
    domain = Domain.find(params[:id])
    @domain_id  = domain.id
    @domain = Unirest.get("#{ENV['API_ROOT_URL']}/#{domain.domain_name}",
                          headers: HEADERS).body
  end 

  def edit
    @domain = Domain.find(id: params[:id])
  end

  def update
    #request creates ALIAS record to NS1
    domain = Domain.find(params[:id])
    response = Unirest.put("#{ENV['API_ROOT_URL']}/#{domain.domain_name}/#{domain.domain_name}/ALIAS
                        ", headers: HEADERS,
                           parameters: { zone: "#{domain.domain_name}", 
                                         domain:"#{domain.domain_name}",
                                          type: "ALIAS",
                                          answers: [{answer: ["#{params[:domain_name]}"]}] }.to_json)
    if response.code == 200 
      domain.update(domain_name: params[:domain_name])
      redirect_to domain_path(domain)
    else
      #error: domain was not successfully changed
      render :edit
    end
  end

  def destroy
    domain = Domain.find(params[:id])
    a_records = domain.a_records
    if domain.user_id == current_user.id
      response = Unirest.delete("#{ENV['API_ROOT_URL']}/#{domain.domain_name}",
                          headers: HEADERS)
        if response.code == 200
          a_records.destroy && domain.destroy
          redirect_to domain_path(domains) 
        end
    else
      redirect_to domain_path(domain) 
    end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
        login(@user)
        redirect_to user_path(@user)
    else
      redirect_to "/login"
    end
  end

  def destroy
    logout    
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
  end

  def create
    user = User.create(email: params[:email], password: params[:password])
    login(user)
    redirect_to user_path(user)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/a_records_helper.rb
module ARecordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/a_records/edit.html.erb
Edit 'A' Record

<%= form_tag "/domains/#{@domain.id}", method: :patch do %> 
  <div>
    <%= text_field_tag :ip_address, nil, placeholder: "New Value" %>
  </div>
  <%= submit_tag "Submit" %>
<% end %>

app/views/a_records/new.html.erb
<h5> Add new 'A' Record </h5>

<%= form_tag domain_a_records_path,  method: :post do  %>
  <div>
    <%= text_field_tag :ip_address%>
  </div>
  <%= submit_tag "Submit" %>
<% end %> 

app/views/a_records/show.html.erb
<h3> 'A' Record for <%= @a_record.domain.domain_name %> </h3>
<br>
<br>
<%= @a_record.ip_address %>
<br>
<br>
<a href="/domains/<%=@a_record.domain_id%>/a_records/<%=@a_record.id%>/edit">Edit Record </a>
<br>
<%= form_tag "/domains/#{params[:domain_id]}/a_records/#{@a_record.id}", method: :delete do %>
    <button type ="submit">Delete Record</button>
<% end %>

app/views/domains/edit.html.erb
Edit Domain Name

<%= form_tag "/domains/#{@domain.id}", method: :patch do %> 
  <div>
    <%= text_field_tag :domain_name, nil, placeholder: "Domain Name" %>
  </div>
  <%= submit_tag "Submit" %>
<% end %>

app/views/domains/new.html.erb
Add New Domain

<%= form_tag '/domains', method: :post do %> 
  <div>
    <%= text_field_tag :domain_name, nil, placeholder: "Domain Name" %>
  </div>
  <%= submit_tag "Create" %>
<% end %>

app/views/domains/show.html.erb
<%= @domain %>
<br>
<br>
<h4> <a href="/domains/<%=@domain_id%>/a_records/new"> Add A Record </h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnsPanel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
Sign Up

<%= form_tag "/users", method: :post do %>
  <div>
    <%= text_field_tag :email, nil, placeholder: "Email" %>
  </div>
  <div>
    <%= password_field_tag :password, nil, placeholder: "Password" %>
  </div>
  <%= submit_tag "Sign Up" %>
<% end %>

<a href="/login"> Log in </a>

app/views/users/show.html.erb
Welcome <%= @user.email %>
<br>
<br>
<h6> Your domains: </h6>
  <% @user.domains.each do |domain| %>
    <a href="/domains/<%= domain.id %>"> <%= domain.domain_name %> </a>
  <% end %>
<br>
<br>
<br>
<a href="/domains/new"> Register new domain </a>
<br>
<a href="/logout"> Log out </a>